import type { Metadata } from "next";
import {Montserrat, Questrial} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const montserrat = Montserrat({subsets: ['latin'] });

const questrial = Questrial({
  subsets: ['latin'],
  weight: ['400', '500', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${inter.className}`}>
        <div className="max-w-[1400px] mx-auto bg-white">
         <Header />  
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}
